my_new_project:
  outputs:
    dev:
      account: fka50167
      database: analytics
      role: Transformer
      threads: 4
      type: snowflake
      warehouse: transforming
      user: <fill-me-in>
      password: <fill-me-in>
      schema: <fill-me-in>
  target: dev
