dbt_modeling_xebia_training:
  outputs:
    dev:
      account: fka50167
      database: analytics
      role: Transformer
      threads: 4
      type: snowflake
      warehouse: transforming
      user: <fill-me>
      password: <fill-me>
      schema: <choose-a-name>
  target: dev
