dbt_modeling_xebia_training:
  outputs:
    dev:
      account: fka50167
      database: analytics
      password: <fill-me>
      role: Transformer
      schema: <choose-a-name>
      threads: 4
      type: snowflake
      user: <fill-me>
      warehouse: transforming
  target: dev
